### ISSUE TITLE
Securely generate the encryption key for new SQLCipher databases

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-android#228]
As part of #221, the encryption key needs to be generated. 

Currently, [there are two naive ways of doing this implemented][1].

Minimally, one of these ways needs to be selected, and audited.

Maximally, this should be re-implemented.

Generating this key would be a good candidate to go into DataProtect. 

/cc @linuxwolf 

[1]: https://github.com/mozilla-lockbox/lockbox-android/blob/6057ba8a4c58f3d59c81b2d605a3d34fe75ce173/app/src/main/java/mozilla/lockbox/support/FxASyncDataStoreSupport.kt#L44

**Comment by jhugman** [comment]
Perhaps part of #168.

**Comment by linuxwolf** [comment]
The current key generation needs to change.  Neither the original nor improved are great; fortunately it appears SQLCipher will perform some form of KDF over the value passed to it in most cases, which increases the key strength a little.

The main issues with the current algorithm are:

* The key length is not a power of two (ideally, 32 or 64 bytes)
* It uses modulo, which can introduce a bias toward the lower end of the range

Using `SecureRandom.nextBytes()` is the right starting point.  From there:
* convert each byte to hex instead of doing a modulo-based lookup; and
* call it with the value of `32` instead of `50`.

**Comment by sandysage** [comment]
@linuxwolf where does this line up for MVP? Is it a must before we publicly launch?

**Comment by linuxwolf** [comment]
This should be done before public launch.
