### ISSUE TITLE
Remove AccountStore network connection checks

### ISSUE THREAD

**Issue by eliserichards** [mozilla-lockbox/lockbox-android#356]
Related to bug https://github.com/mozilla-lockbox/lockbox-android/issues/350
Related to #185 
Related to #314 
Related to #330 
Related to #342 

Remove the temporary error handling in the `AccountStore` that was implemented in anticipation of our internal alpha launch. Utilize the `NetworkStore` created as part of #185.

Be more specific about the error types we handle (now in latest application-services), not just all of them...

**Comment by devinreams** [comment]
Because the FxA store now provides us with more specific detail (network vs other failures) we can update to be more specific...

"Should just be adding an if statement for now..."

Can also consider stopping throwing the dialog entirely (leaving just the bar). Can handle just at log level.

Over communicating is better than under so can consider punting post launch.
