### ISSUE TITLE
User is always kicked back to the Entries List when foregrounding app

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-android#380]
If the user is viewing an Entry Detail, and switches apps to paste a credential, when they return they are brought back to the Entry List. This is problematic as they then have to find and go back to the entry they were using.

It would be ideal to always bring the user back to the screen they were last viewing when foregrounding the app. This is how we handle this for iOS.

@sashei analysis "unlock always pushes to go to entry list"

**Comment by sandysage** [comment]
This is a broken experience for anyone who is using copy/paste

**Comment by sashei** [comment]
I'm no longer able to reproduce this after #435

**Comment by devinreams** [comment]
I was able to complete the desired user experience successfully:

- open entry list
- open entry
- tap to copy username
- background Lockbox
- open another app
- paste username
- use switcher to go back to Lockbox
- copy password
- use switcher to return to other app
- paste password

I was also able to do the same without using the switcher (just background the app, go to home screen app launcher screen, open other app).

I propose we close this as "fixed" unless anyone encounters otherwise...

**Comment by nickbrandt** [comment]
@devinreams @sashei yep this is working as desired for me as well 👍
