### ISSUE TITLE
Firefox saved login not syncing to Lockbox

### ISSUE THREAD

**Issue by bsterne** [mozilla-lockbox/lockbox-android#434]
I'm running Lockbox in Android Studio emulator, and after an initial sync which did copy over all existing saved logins from Firefox, any new logins don't seem to sync over.

In Firefox, under Saved Logins, I see 5 accounts, including one chrome:// URL for Firefox Sync itself, 3 existing logins, and one login that I added today after launching Lockbox.

Only the three previously existing logins synced into Lockbox. Even after restarting the emulator, I only see the 3 old logins. I worked around (presumably) #415 by disconnecting and reconnecting my Sync account, but I still only see the 3 logins. How do I get new stored logins to show up in my Lockbox list?

**Comment by devinreams** [comment]
Sorry for the troubles @bsterne. We are actively hammering out some bugs that may be related, so work arounds may be needed in the short term...

Seems like you’ve tried the obvious:

- pull to refresh
- force quit and re-open
- disconnect and sign back in

Can you please also try fully clearing the app data/cache and re-installing the app?

It may not matter as there may be a datastore state that’s out of sync. Once #435 is finished we may be in better shape (less variables to control) to try and re-test and reproduce. :construction:

**Comment by bsterne** [comment]
Hey @devinreams. No worries at all.
All three of those actions don't sync the new passwords that I've added from another device. That said, several days after I filed this issue, the "new" login (now several days old) did sync over into the list. Can you suggest ways I can debug this? How do I get a canonical list of logins that have synced to my Firefox Sync account? It's possible, for example, that they are stored in my local Firefox profile, but haven't synced to the central server. In any case, it's impossible for me to determine what happened in the past 4 days since I filed this issue that allowed the new items to sync over.

**Comment by bsterne** [comment]
So, I just created a new Firefox profile and synced it with the account, and only the "old" logins synced to the new profile. This tells me that I'm misunderstanding how Firefox Sync works, e.g. the client sync works on a longer interval than I expected, or there is something misconfigured in Firefox.

@devinreams do you have any perspective on how quickly, Lockbox aside, a login added in one Fx profile should sync to another profile?

**Comment by bsterne** [comment]
Okay, I found the Fx UI for "Sync Now", and when I manually synced from the profile, then pulled to refresh in Lockbox, the new item showed up. So, that tells me there is a longer automatic client sync interval than I assumed. Should I be thinking about the sync timing differently? I haven't found any clear documentation (only some conflicting SUMO pages). We may be able to close this issue if it's simply a matter of my other clients not syncing new logins to the server immediately.

**Comment by devinreams** [comment]
>I found the Fx UI for "Sync Now", and when I manually synced from the profile, then pulled to refresh in Lockbox, the new item showed up. So, that tells me there is a longer automatic client sync interval than I assumed. Should I be thinking about the sync timing differently?

Hey @bsterne, you're right the desktop-to-Sync mechanisms may not be what you or other users expect from sync service. In short: yes when you make local changes like saving a password, they may not be immediately relayed up to our Sync service, furthermore they may not be immediately retrieved back down into your apps or other devices.

As you noticed, if you "force" a sync from your local (desktop or mobile) Firefox instance then force sync/refresh in an app like Lockbox you _should_ see the results fairly immediately. Otherwise, we weigh the cost/benefit of sending and receiving semi-regular updates so its not easy to predict when you'll see your login appear in Lockbox without some manual intervention.

While not ideal. I believe, based on the fact you did ultimately see your new saved login in Lockbox, this can be closed as it's working as expected. If you have more to share or questions please feel free to let us know. 😁
