### ISSUE TITLE
Implement explicit app initialization behavior

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-android#435]
Implement an explicit initialization stage to start the app's "source of truth".  This may involve any of the following:

* An explicit SplashFragment (+ SplashPresenter) which replaces itself with the "true" starting fragment (locked, welcome, itemlist)
* Code that examines necessary stored data (e.g., Stores that read from prefs?) and takes steps to ensure all stores are fully initialized (e.g., The DataStore is Locked/Unlocked/Unprepared)
* Stores that fully initialize themselves dispatch actions that will further initialize other stores
* Stores read (e.g., `take(1).subscribe(...)`) state from other stores to initialize their state

Currently when the application starts up, the initial state of some stores is left undetermined until other actions are dispatched and handled.  This has resulted in initialization being distributed and in some cases implicit, and is believed to be the cause of many of the inconsistency and "broken-ness" experienced.

Related to #260 
Related to #323 
Related to #360 
Related to #415 

Cases:
- [x] startup with no account => welcome
- [x] foreground with no account after ~5 minutes => stays on previous screen ?
- [x] startup with no account, login, onboarding => itemlist
- [x] startup with account, later than lock time => lock screen
- [x] foreground with account, later than lock time => lock screen
- [x] manually lock, hit back button, foreground => lock screen
- [x] startup with account, before lock time => itemlist
- [x] foreground with account, before lock time => stays on previous screen
- [x] unlock with fullscreen system prompt from lock screen => itemlist
- [x] unlock with fingerprint from lock screen => itemlist

**Comment by sashei** [comment]
Thoughts from 🍐 w/ @eliserichards :

Ideally, we'd like the initialization of app state to correspond with an initialization of the `DataStore`. Rather than having the `DataStore` wait passively for dispatched initialization actions, shift as much of the querying / initialization / foregrounding logic as possible into the `DataStore.init` method. The other relevant stores we need to have in this scenario are the `AccountStore` and the `AutoLockStore`. Ideas:

- `AutoLockStore`: change the `autoLockRequired` variable to a `Boolean` rather than an `Observable<Boolean>` and have the `DataStore` query that only when appropriate (i.e., foreground, app start). 
- `AccountStore`: either have this store dispatch the `UpdateCredentials` action a la #413 , OR have the `DataStore`subscribe to the `syncCredentials` observable and do state management appropriately

**Comment by sashei** [comment]
Aside: make sure to clear autolocktime value on user reset, so that we don't have erronious locking when the user disconnects their account

**Comment by sashei** [comment]
Task switching vs. app switching as a way to mitigate the `LifecycleAction.Foreground` problem when returning from a system authentication prompt?

**Comment by jhugman** [comment]
From the Android engineering meeting: 

 * it is just not possible to distinguish between shelling out the a system activity (e.g. PIN guard) and the user pressing the home button.
 * we should not be relying detecting the user's idea of what foregrounding and backgrounding of the app to drive the autolock store.
 * we should document the `LifecycleAction.Foreground` and `LifecycleAction.Background` actions as app/activity focused, and introduce new events for autofill start and end.
