### ISSUE TITLE
Visual Tidy DataSet presentation XML for autofill

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockbox/lockbox-android#436]
Followup from #413 

The priority for landing #413 is such that the implementation of the popup is not consistent with the designs.

### Visual Design

**InVision**
Initial (1 entry): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564412_Autofill_-_App_-_Initial
Initial (multiple entries): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564409_Autofill_-_App_-_Initial_-multiple_Entries-
Initial (no matching entries): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317568427_Autofill_-_App_-_No_Matches
Unlock (fingerprint): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564407_Autofill_-_App_-_Unlock_-_Fingerprint
Unlock (Device PIN/Pattern): https://mozilla.invisionapp.com/share/3SN35UHWJDX#/310610372_Lock_Screen_-_Device_PIN
Filled: https://mozilla.invisionapp.com/share/3SN35UHWJDX#/317564408_Autofill_-_App_-_Filled

**Zeplin**
Initial (1 entry): https://zpl.io/2pBe6lE
Initial (multiple entries): https://zpl.io/aNo8g9v
Initial (no matching entries): https://zpl.io/a7ENAJR
Unlock (fingerprint): https://zpl.io/bLD0zx7
Unlock (Device PIN/Pattern): https://zpl.io/bAqXRm6

**Comment by eliserichards** [comment]
I would love to get some feedback on what I'm doing for the autofill popup with multiple entries. Currently the designs show the hostname/title (e.g. "github.com") before each entry in the list. I'm having trouble doing that implementation, but I am able to put a header at the top of the list, like this: 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/43795363/53673302-6d89df80-3c3b-11e9-8a3c-2a9c7631e396.png"> 

I'd love implementation input from @sashei / @jhugman since they've been touching the autofill code, and also @changecourse for design.

**Comment by jhugman** [comment]
@changecourse Hi; could I have an asset for "Unlock Firefox Lockbox" please.

**Comment by changecourse** [comment]
Assets should all be uploaded to Zeplin and available for export (from the description)

@jhugman Is there a specific asset that is missing?

**Comment by linuxwolf** [comment]
@changecourse there is a gap between the provided designs and the implementation capabilities: "App - Unlock required".  This occurs when Android requests autofill items for an app, but Lockbox needs to be unlocked before it can do so.

Currently on `master`, it displays (and only displays) "Unlock Firefox Lockbox" prefixed with the Lockbox app icon.  The request is for what to display in this variant of the "App - No matching entries"
