### ISSUE TITLE
Set up automated testing infrastructure exploration

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#50]
Considering...
* [x] CI infrastructure (bitrise) #66 
* [x] integration testing (espresso)
* [x] Simulator containers ("Virtual Device Testing" step in bitrise)
  - https://discuss.bitrise.io/t/how-to-run-android-ui-tests-on-virtual-devices/2496

**Comment by devinreams** [comment]
We have linting, unit testing, and now: device testing!
https://app.bitrise.io/build/0c347bb5d9e60fa7

<img width="1237" alt="screen shot 2018-09-18 at 2 16 45 pm" src="https://user-images.githubusercontent.com/49511/45713937-8438f000-bb4d-11e8-8cae-a6449709b88f.png">

**Comment by devinreams** [comment]
Closing out with a commit to add the bitrise badge to the read since we are automatically running:

- Android unit test
- Android lint
- Gradle debug and test build
- espresso / virtual device test (opens and gets that first screenshot)

I think we can say our automated testing infrastructure is in place.
