### ISSUE TITLE
Toggle to enable/disable sending metrics (settings)

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-android#8]
As a user I want to disable the ability to send usage / Telemetry data to Mozilla Firefox.

## Acceptance Criteria
- [ ] Should use the same style as Firefox Android.
- [ ] Should default “Send Usage Data” to enabled.
- [ ] If disabled, should stop sending any and all events.

### Visual Design

**InVision**
https://mozilla.invisionapp.com/share/3SN35UHWJDX#/309979885_Settings

**Zeplin**
https://zpl.io/awYA3LK

depends on #6

**Comment by eliserichards** [comment]
Todo:
- [ ] set up telemetry store so that it’s listening to the sharedprefs
- [ ] persist the new value of the toggle in the SettingStore
- [ ] is android config running in debug mode? -> make sure it’s off
- [ ] update SectionedAdapterTests
- [ ] update SettingListAdapterTests
- [ ] SettingStoreTests
- [ ] TelemetryStoreTests - change to reflect updates to applyContext()
